//go:generate goldigen --in "../config/types.yml" --out "dependency_injection.go" --package app/lib --function RegisterTypes --overwrite --nointeraction
package lib

import (
	"app/service"
	"github.com/fgrosse/goldi"
)

// RegisterTypes registers all types that have been defined in the file "../config/types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v0.9.9.
// It is however good practice to put this file under version control.
// See https://github.com/fgrosse/goldi for what is going on here.
func RegisterTypes(types goldi.TypeRegistry) {
	types.RegisterAll(map[string]goldi.TypeFactory{
		"injected": goldi.NewStructType(new(service.Injected)),
		"service":  goldi.NewStructType(new(service.ServiceImpl), "@injected"),
	})
}
